feign:
  url:
    prefix: http://localhost:8080/target_server # DemoFeignClient ?? ??? url prefix ?
  client:
    config:
      default:
        connectTimeout: 1000
        read-timeout: 3000
        loggerLevel: NONE
      demo-client: # DemoFeignClient ?? ??? Client ?? ?
        connectTimeout: 1000
        read-timeout: 3000
        loggerLevel: HEADERS # ??? ??? ?? FeignCustomLogger -> Logger.Level logLevel ??? ???
